services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=tradeshipdb
      - POSTGRES_USER=paolo
      - POSTGRES_PASSWORD=admin123
    volumes:
      - "tradeship_pgsql:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "tradeshipdb", "-U", "paolo"]
      retries: 3
      timeout: 5s

  mailhog:
    image: "mailhog/mailhog:latest"
    platform: linux/amd64
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://paolo:admin123@db:5432/tradeshipdb?schema=public
      - JWT_SECRET=bd40bda70a2305eb1c49bbb959984af7777615add5811da3a40c6ac09cb08872bc85dfa8
      - JWT_REFRESH_SECRET=bd40bda70a2305eb1c49bbb959984af7777615add5811da3a40c6ac09cb08872bc85dfa8
      - JWT_EXPIRES_IN=7d
      - JWT_REFRESH_EXPIRES_IN=30d
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - db
      - mailhog
    networks:
      - default
    volumes:
      - .:/app
      - /app/node_modules

networks:
  default:
    driver: bridge
volumes:
  tradeship_pgsql:
    driver: local
