# Generated by Django 5.2.6 on 2025-09-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingpreferences',
            name='preferred_carrier',
            field=models.CharField(choices=[('usps', 'USPS'), ('ups', 'UPS'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('other', 'Other')], default='usps', help_text='Preferred shipping carrier', max_length=20),
        ),
    ]
