# Generated by Django 5.2.6 on 2025-09-16 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_trade', '0002_alter_shippingpreferences_preferred_carrier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Interest/tag name', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the interest/tag')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for UI display', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this interest/tag is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1-5 stars')),
                ('description', models.TextField(help_text='Description of the trade experience')),
                ('would_trade_again', models.BooleanField(default=True, help_text='Would trade with this person again')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='apps_trade__tags_e9ef70_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['name'], name='apps_trade__name_3d8a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['is_active'], name='apps_trade__is_acti_3fee87_idx'),
        ),
        migrations.AddField(
            model_name='item',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text='Item interests/tags', related_name='items', to='apps_trade.interest'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_trader',
            field=models.ForeignKey(help_text='User being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(help_text='User giving the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='trade',
            field=models.ForeignKey(help_text='The trade being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apps_trade.trade'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['trade'], name='apps_trade__trade_i_dfdefb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer'], name='apps_trade__reviewe_72ffbf_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewed_trader'], name='apps_trade__reviewe_65083c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='apps_trade__rating_58dea6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='apps_trade__created_e1ad9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('trade', 'reviewer')},
        ),
    ]
