# Generated by Django 5.2.6 on 2025-09-16 13:23

from django.db import migrations


def create_initial_interests(apps, schema_editor):
    """Create initial interest/tag data"""
    Interest = apps.get_model('apps_trade', 'Interest')

    interests_data = [
        {'name': 'Electronics', 'description': 'Electronic devices, gadgets, and tech items', 'color': '#007bff'},
        {'name': 'Clothing', 'description': 'Apparel, fashion items, and accessories', 'color': '#28a745'},
        {'name': 'Books', 'description': 'Books, magazines, and reading materials', 'color': '#ffc107'},
        {'name': 'Home & Garden', 'description': 'Home decor, garden tools, and household items', 'color': '#17a2b8'},
        {'name': 'Sports & Outdoors', 'description': 'Sports equipment and outdoor gear', 'color': '#dc3545'},
        {'name': 'Toys & Games', 'description': 'Toys, board games, and entertainment items', 'color': '#fd7e14'},
        {'name': 'Collectibles', 'description': 'Rare items, antiques, and collectible pieces', 'color': '#6f42c1'},
        {'name': 'Jewelry', 'description': 'Jewelry, watches, and precious items', 'color': '#e83e8c'},
        {'name': 'Art & Crafts', 'description': 'Artwork, craft supplies, and creative materials', 'color': '#20c997'},
        {'name': 'Other', 'description': 'Miscellaneous items and uncategorized goods', 'color': '#6c757d'},
    ]

    for interest_data in interests_data:
        Interest.objects.get_or_create(
            name=interest_data['name'],
            defaults={
                'description': interest_data['description'],
                'color': interest_data['color']
            }
        )


def reverse_create_interests(apps, schema_editor):
    """Remove the created interests"""
    Interest = apps.get_model('apps_trade', 'Interest')
    Interest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('apps_trade', '0003_interest_review_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_interests, reverse_create_interests),
    ]
