# Generated by Django 5.2.6 on 2025-09-20 14:03

import apps.trade.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_trade', '0004_auto_20250916_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Item file attachment', upload_to=apps.trade.models.upload_item_file_path)),
                ('name', models.CharField(help_text='File name/description', max_length=200)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('certificate', 'Certificate'), ('manual', 'Manual'), ('receipt', 'Receipt'), ('warranty', 'Warranty'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', help_text='Type of file', max_length=20)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the file content')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this file can be viewed by other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='apps_trade.item')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item'], name='apps_trade__item_id_68c47f_idx'), models.Index(fields=['file_type'], name='apps_trade__file_ty_60da66_idx'), models.Index(fields=['is_public'], name='apps_trade__is_publ_33d7f3_idx')],
            },
        ),
    ]
