# Generated by Django 5.2.6 on 2025-09-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0001_initial'),
        ('apps_trade', '0004_auto_20250916_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text="User's interests/tags for matching with relevant items", related_name='users', to='apps_trade.interest'),
        ),
    ]
