from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    NotificationTypeViewSet,
    NotificationUserSettingsViewSet,
    NotificationViewSet,
    NotificationBatchViewSet,
    ConversationViewSet,
    ChatMessageViewSet
)

# Create router and register viewsets
router = DefaultRouter()
router.register(r'types', NotificationTypeViewSet, basename='notification-types')
router.register(r'settings', NotificationUserSettingsViewSet, basename='notification-settings')
router.register(r'notifications', NotificationViewSet, basename='notifications')
router.register(r'batches', NotificationBatchViewSet, basename='notification-batches')
router.register(r'conversations', ConversationViewSet, basename='conversations')
router.register(r'messages', ChatMessageViewSet, basename='chat-messages')

app_name = 'notification'

urlpatterns = [
    path('', include(router.urls)),
]

# URL patterns generated by the router:
# GET /types/ - List notification types
# GET /types/{id}/ - Get specific notification type
# GET /types/choices/ - Get notification type choices

# GET /settings/ - List user notification settings
# POST /settings/ - Create notification setting
# GET /settings/{id}/ - Get specific setting
# PUT /settings/{id}/ - Update setting
# DELETE /settings/{id}/ - Delete setting
# GET /settings/preferences/ - Get structured preferences
# POST /settings/update_preferences/ - Update preferences

# GET /notifications/ - List user notifications (with filters)
# POST /notifications/ - Create notification
# GET /notifications/{id}/ - Get specific notification
# PUT /notifications/{id}/ - Update notification
# DELETE /notifications/{id}/ - Delete notification
# POST /notifications/{id}/mark_read/ - Mark as read
# POST /notifications/{id}/mark_unread/ - Mark as unread
# POST /notifications/mark_multiple/ - Mark multiple as read/unread
# POST /notifications/mark_all_read/ - Mark all as read
# GET /notifications/unread_count/ - Get unread count
# GET /notifications/statistics/ - Get notification statistics
# DELETE /notifications/clear_read/ - Delete all read notifications
# DELETE /notifications/clear_old/ - Delete old notifications

# GET /batches/ - List notification batches (staff only)
# POST /batches/ - Create batch (staff only)
# GET /batches/{id}/ - Get specific batch
# PUT /batches/{id}/ - Update batch
# DELETE /batches/{id}/ - Delete batch
# GET /batches/{id}/recipients/ - Get batch recipients
# POST /batches/{id}/send/ - Send batch

# GET /conversations/ - List user conversations
# POST /conversations/ - Create conversation
# GET /conversations/{id}/ - Get specific conversation
# PUT /conversations/{id}/ - Update conversation
# DELETE /conversations/{id}/ - Delete/archive conversation
# GET /conversations/{id}/messages/ - Get conversation messages

# GET /messages/ - List user messages
# POST /messages/ - Send message
# GET /messages/{id}/ - Get specific message
# PUT /messages/{id}/ - Update message
# DELETE /messages/{id}/ - Delete message
# POST /messages/mark_as_read/ - Mark messages as read
